# This clippys, docs, tests, builds.

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "full"
  RUST_MIN_STACK: 8000000

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019, macos-11, ubuntu-20.04]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Cache
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ matrix.pkg }}-clippy

    - name: Install dependencies
      run: |
        rustup update
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt update
          sudo apt install -y libgtk-3-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          rustup target add aarch64-apple-darwin
        fi
      shell: bash

    - name: Clippy
      run: cargo clippy --release

    - name: Test
      run: cargo test --all-features

    - name: Build
      shell: bash
      run: |
        # ARM builds.
        if [ "$RUNNER_OS" == "macOS" ]; then
          cargo build --release --target aarch64-apple-darwin
        fi
        cargo build --release

    - name: Compress (GUI)
      shell: bash
      run: |
        mkdir OUTPUT
        VERSION=$(grep -m1 "version" Cargo.toml | grep -o "[0-9].[0-9].[0-9]")

        if [ "$RUNNER_OS" == "Linux" ]; then
          # Tar
          tar -czpf "monero-vanity-v${VERSION}-linux-x64.tar.gz" target/release/monero-vanity
          mv "monero-vanity-v${VERSION}-linux-x64.tar.gz" OUTPUT/
        elif [ "$RUNNER_OS" == "macOS" ]; then
          # x64
          tar -czpf "monero-vanity-v${VERSION}-macos-x64.tar.gz" target/release/monero-vanity
          mv "monero-vanity-v${VERSION}-macos-x64.tar.gz" OUTPUT/

          # ARM64
          tar -czpf "monero-vanity-v${VERSION}-macos-arm64.tar.gz" target/aarch64-apple-darwin/release/monero-vanity
          mv "monero-vanity-v${VERSION}-macos-arm64.tar.gz" OUTPUT/
        elif [ "$RUNNER_OS" == "Windows" ]; then
          # Zip
          cd target/release
          powershell Compress-Archive -LiteralPath monero-vanity.exe -DestinationPath "monero-vanity-v${VERSION}-windows-x64.zip"
          mv "monero-vanity-v${VERSION}-windows-x64.zip" ../../OUTPUT/
        fi

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: OUTPUT
